version: '3.7'

services:
    controller:
      image: onos:latest
      build:
        context: .
        dockerfile: Onos.Dockerfile
      network_mode: "host"
      privileged: true
      restart: always
      volumes:
        - ./data/onos:/backup
